name: EnderTeamBattle
version: '${version}'

main: io.twotle.Enderteambattle
api-version: '26.2'
load: POSTWORLD

commands:
  etb:
    description: EnderTeamBattle 관리 명령어
    usage: /etb <init|start|pause|stop|team>
    permission: enderteambattle.admin

permissions:
  enderteambattle.admin:
    description: EnderTeamBattle의 모든 관리 명령어를 사용할 수 있습니다.
    default: op
